name: "mvdream-decorgan-sd21-rescale0.5-single"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-multiview-camera-datamodule"
data:
  batch_size: [8, 4, 4] # must be dividable by n_view
  n_view: 4
  # 0-4999: 64x64, >=5000: 128x128
  width: [64, 128, 256]
  height: [64, 128, 256]
  resolution_milestones: [5000, 10000]
  camera_distance_range: [0.8, 1.0] # relative
  fovy_range: [15, 60]
  elevation_range: [0, 30]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  n_val_views: 4
  eval_camera_distance: 3.0 # try 3.0 / 4.0
  eval_fovy_deg: 40.
  eval_elevation_deg: 15.

system_type: "decorgan-system"
system:
  geometry_type: "voxel-grid-single"
  geometry:
    radius: 1.0
    normal_type: "finite_difference"

    density_activation: softplus
    grid_size: [32, 32, 32]
    n_feature_dims: 3
    category: "00000000_animal"
    upsample_rate: 4
    downsample_rate: 16
    regularization: true

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid
    requires_normal: true

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    share_aug_bg: true

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512 # 128 for 256x256 image and 256 for 128x128 image, otherwise OOM
    grid_prune: false
    return_comp_normal: true

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "multiview-diffusion-guidance"
  guidance:
    model_name: "sd-v2.1-base-4view"
    ckpt_path: null # path to a pre-downloaded checkpoint file (null for loading from URL)
    guidance_scale: 50.0
    min_step_percent: [0, 0.98, 0.02, 8000]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [0, 0.98, 0.50, 8000]
    recon_loss: true
    recon_std_rescale: 0.5

  loggers:
    wandb:
      enable: false
      project: "threestudio"

  loss:
    lambda_sds: 1.
    lambda_orient: 0.
    lambda_sparsity: 0.
    lambda_opaque: 0.
    lambda_z_variance: 0.
    lambda_reg_2d: [0, 10000, 10, 8000]
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.0001
      background:
        lr: 0.00001

trainer:
  max_steps: 15000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 1000
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
